### ISSUE TITLE
Сборка

### ISSUE THREAD

**Issue by avasyukov** [tyurinatanya/AvlTreeClass#1]
Формально сейчас проект не собирается. Но при этом написан очень чисто, и я могу его собрать после очень небольших правок.

Возможно, я просто что-то не знаю о том, чем/как его предполагалось собирать?

**Comment by tyurinatanya** [comment]
Здравствуйте! Сейчас вроде должно нормально быть, просто забыла про то, что
шаблонные классы должны быть реализованы сразу в хэдере

пт, 15 мая 2020 г., 3:39 Alexey Vasyukov <notifications@github.com>:

**Comment by avasyukov** [comment]
Подтверждаю, починено
