### ISSUE TITLE
(*) Реюзабельность компонента в большом проекте

### ISSUE THREAD

**Issue by avasyukov** [tyurinatanya/AvlTreeClass#2]
_Вопрос не срочный. Вопрос не является критичным багом. Вопрос можно отложить до 20го или до зачёта._

Допустим, теперь хочется использовать написанное дерево в некотором проекте. В проекте есть не только тестовый main, но и ещё какие-то классы. И все они хотят использовать дерево для хранения своих данных.

Каркас модельного проекта - https://github.com/avasyukov/AvlTreeClass
Это форк ровно вашего репозитория, в который я добавил один коммит, вот такой - https://github.com/avasyukov/AvlTreeClass/commit/8426e9479790f4637e8e55acefbfa4edf141d645

Смысл коммита:
- я создал два класса: `A` и `B`, каждый из них в своих полях держит `AvlTree<int>`
- в `main` я создаю по одному экземпляру `A` и `B`
- реализации `A` и `B` добавлены в `CMakeLists.txt`

И оно теперь внезапно не собирается.

Нужно прочитать и осознать сообщения при сборке, после чего поправить структуру компонента `AvlTree`, чтобы его стало можно использовать в такой ситуации.

**Comment by tyurinatanya** [comment]
Здравствуйте! Теперь exception имеет отдельную реализацию, чтобы избежать
multiple definition (реализация дописана в CMakeLists). Подобного
исправления достаточно?

пт, 15 мая 2020 г. в 16:28, Alexey Vasyukov <notifications@github.com>:

**Comment by avasyukov** [comment]
Это было быстро. Да, всё стало совсем прекрасно.
